server:
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/picpaydb
    username: root
    password: 32412294
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: false
  properties:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      mode: always
